### ISSUE TITLE
Newer cheerio versions remove CheerioStatic as a type

### ISSUE THREAD

**Issue by arossetter** [maael/temtem-api#108]
So as the title says, doing a fresh clone of the repo along with npm install, you actually get back a version of cheerio that doesn't contain the CheerioStatic interface. I did some digging and it appears as though the cause is how the node package is retrieving versions...

`"devDependencies": {
    "@types/cheerio": "^0.22.15",
    "@types/glob": "^7.1.3",
    "@types/isomorphic-fetch": "^0.0.35",
    "@types/node": "^12.12.6",
    "@types/react": "^16.9.11",
    "@types/sharp": "^0.28.0",
    "cheerio": "^1.0.0-rc.3",
    "cli-progress": "^3.8.2",
    "glob": "^7.1.6",
    "husky": "^4.2.1",
    "jimp": "^0.16.1",
    "prettier": "^2.2.1",
    "pretty-quick": "^2.0.1",
    "sharp": "^0.28.1",
    "simple-git": "^1.130.0",
    "throat": "^5.0.0",
    "ts-node": "^8.6.2",
    "tslint": "^5.20.1",
    "typescript": "^3.7.2"
  }`

All of those carats are returning those or later versions in the tree (for instance, IIRC the cheerio version that gets pulled with an npm install is actually cheerio 1.3.0). This caused me a few headaches while I was figuring out what was happening. Turns out that removing the carats fixed the issue for me and I was able to run the npm scripts right off the bat. Note that this is an issue and not a PR just because I removed ALL carats, not just the ones pertaining to cheerio, and that is most likely overkill. Will need to run a couple tests to see what exactly should be kept on an explicit version vs can be upgraded.

**Comment by maael** [comment]
Hmm, that's pretty odd, I recently clean installed this project on a new PC, so it should have been a similar experience, except I had no issues. Did you use `npm` instead of `yarn` perhaps? Or what version of `node`/`yarn` did you use? I see you mention `npm install`, that won't respect the `yarn.lock` file, so you'll get whack versions, if you install the packages with `yarn` like suggested on the `README.md`, you should get the right versions. The `package.json` has the ranges, while the lock file (`yarn.lock` here as I generally use `yarn`), tightens it up more.

Even more odd is there isn't a published version `1.3.0` of `cheerio`? The latest is `1.0.0-rc.10`/`0.22.30` for the actual package and types respectively. And the latest version of `cheerio` fails to build, as they're using [type only imports](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export) from TS 3.8.0, while we're using TS 3.7.X here, so don't have that feature yet.

I'll try bumping cheerio/typescript to their latest version and see what happens.

In the mean time, could you try cleaning out the `node_modules` and using `yarn` to install, and see if that causes issues?

**Comment by arossetter** [comment]
It's exactly as you say. I did use `npm` as opposed to `yarn` and I can confirm that using `yarn` did grab the correct dependencies. I'll close out my issue, and maybe read the docs a little closer next time. 😉

**Comment by maael** [comment]
No worries, thanks for reporting back, and good to hear it worked. Gave me a nudge to update it all anyway, bumped `cheerio` up to the latest in https://github.com/maael/temtem-api/pull/111.
