### ISSUE TITLE
Mistake in 'targets' specifically on the technique "Toxic Plume"

### ISSUE THREAD

**Issue by ToddGeorgeKelly** [maael/temtem-api#13]
For some reason, the API is filling the 'targets' field with one of the both of the strings from the 'effects' fields in the technique's synergy effects. The Wiki is showing the information correctly, though.

```
{
    "name": "Toxic Plume",
    "wikiUrl": "https://temtem.gamepedia.com/Toxic_Plume",
    "type": "Toxic",
    "class": "Special",
    "damage": 50,
    "staminaCost": 24,
    "hold": 1,
    "priority": "normal",
    "synergy": "Crystal",
    "synergyEffects": [
      {
        "effect": "-8 STA",
        "type": "buff",
        "damage": 0
      },
      {
        "effect": "Targets get ATK-",
        "type": "debuff",
        "damage": 0
      }
    ],
    "targets": "-8 STA, Targets get ATK-",
    "description": "Like a faulty airship engine, this Temtem can leave a trail of toxic gas that gives Poison to the whole team for 1 turn."
  },
```

**Comment by maael** [comment]
Hi, thanks for the feedback and reporting this, I'll try to look at it today. It's likely just some minor HTML differences that I'll need to account for and make the data collection more resilient against.

**Comment by maael** [comment]
I looked into this, and it was due to an issue when getting the data for techniques, basically there is a function that gets the rows in the info box (the thing at the top of wiki pages with info and an image in), and gets the data for a given row in it. However it was doing this by looking for text anywhere in the row, rather than by the title. So when trying to get the data for the row named `Targets`, because `Targets` is in Toxic Plume's synergy effect, it got that first.

I've changed it so it fetches it actually based on the title of the row, not the content. It also checks for completely matching text, not just that the expected title is included somewhere.

I've refreshed the technique data so this is fixed for Toxic Plume, and the changes I've made should mean this doesn't happen again.
