### ISSUE TITLE
Endpoint /api/techniques returns technique categories instead of individual techniques

### ISSUE THREAD

**Issue by Piaomu** [maael/temtem-api#133]
The documentation says techniques should return with this JSON structure:
![image](https://user-images.githubusercontent.com/77030627/190862702-c7798e2c-3c7f-48fb-90b0-51b47efae2c8.png)

However, calling the endpoint returns this structure (with url included for sanity check):
![image](https://user-images.githubusercontent.com/77030627/190863404-6b431473-12ae-4e42-98a7-0cf765f23aa2.png)

EDIT:

The JSON structure is correct, but the data is not.

Techniques are not returning as expected.

**Comment by maael** [comment]
Hey there, thanks for reporting! This was likely due to the wiki changing format.

Today I've pointed to the new wiki as a data source, and the techniques seem to be collected and reporting correctly in the API.

![chrome_LfVBPgcvzj](https://user-images.githubusercontent.com/5610674/190913643-a624e2e9-d470-42ce-a7af-abf8ff4c0d53.png)



I'm going to mark this as closed, but please re-open if you feel it isn't.
