### ISSUE TITLE
Locations - Temtem

### ISSUE THREAD

**Issue by Chibuso** [maael/temtem-api#15]
I notice that there is no data for temtem found in all Locations except for Deniz. Is there a reason for this?

**Comment by maael** [comment]
Hey! Thanks for taking a look at the API.

The reason for this is because the API gets data from the official wiki, and the wiki page for Deniz has a Temtem list on it ([see here](https://temtem.gamepedia.com/Deniz#Temtem)) while the other Islands like [Tucma](https://temtem.gamepedia.com/Tucma) don't, and unreleased islands don't either.

Though looking through, Omninesia has a Temtem list on its wiki page, so should have a Temtem list but the API hasn't picked it up, so I'll look into that.

To make those lists more reliable I think what I'll do is I'll extract the location information from the individual temtem, as they seem to be more reliable and up to date.

**Comment by maael** [comment]
Hey, I've done the change I mentioned previously, so now the islands under [/api/locations](https://temtem-api.mael.tech/api/locations) include a list of temtem, if the island is one that's been released (so at the moment Deniz, Omninesia, and Tucma).

How does that look to you?

**Comment by maael** [comment]
I'm going to close this, but feel free to reopen it if it isn't fixed how you think it should be.
