### ISSUE TITLE
Weaknesses value are strength value

### ISSUE THREAD

**Issue by xTiborius** [maael/temtem-api#19]
Hi,

the weakness list contains the values for the strength.
Fire has 2x with water but in the list stay 0.5.

br Tibor

**Comment by maael** [comment]
Hi,

You can find the table this data comes from [here on the wiki](https://temtem.gamepedia.com/Temtem_Types#Strengths_and_Weaknesses).

Potentially this is a case of bad naming, the endpoint should maybe be `/api/type-table`, or `/api/strengths` or something, but the table that this data would drive are commonly called weakness tables, which is why I used `/api/weaknesses`.

The top level key of the table is the attacking temtem type, and the fields under that are the defending types, and the values are the resulting multiplier.

I'll add a comment on the docs page explaining as much.

While I won't change or edit this endpoint incase other people are using it, I can make the data available under a different endpoint if you want, something like `/api/strengths` or `/api/type-table`? What do you think?

**Comment by xTiborius** [comment]
You don't have to change anything on purpose for me. Just wanted to make sure it was public knowledge.

**Comment by maael** [comment]
I've added a comment on the docs page [here](https://temtem-api.mael.tech/#/api/weaknesses) to make people aware hopefully, so I'll just close this for now then.
