### ISSUE TITLE
Temtem Height & Weight

### ISSUE THREAD

**Issue by Chibuso** [maael/temtem-api#2]
This is a new issue as of today, I noticed that all of the temtem height & weight values have been replaced with 0. Not sure why.

**Comment by maael** [comment]
Hey, thanks for reporting this! I've fixed it now.

It was introduced because the wiki got changed so the height/weight HTML was a bit different.

I've fixed it in https://github.com/maael/temtem-api/commit/720a8c9875d5a518ae0c0b25c3bbfe2c3abd42ca.

In the README there's a TODO to try to make the API more stable so it won't release breaking changes to try to stop this happening in the future.
