### ISSUE TITLE
knownTemtemSpecies.json is empty

### ISSUE THREAD

**Issue by TiboriusDev** [maael/temtem-api#59]
knownTemtemSpecies.json is empty

**Comment by maael** [comment]
Manually fixed in https://github.com/maael/temtem-api/commit/b2c34c4d06f9bc8e358ce43a1bc91dc9b888acf2. Broke because the wiki authors keep moving the page the temtem species list is on. I will make this less brittle in the future, so it doesn't update it if it empties the list, and tries the two pages they keep moving it between.

**Comment by maael** [comment]
This has been fixed in https://github.com/maael/temtem-api/pull/60 now, we check all the urls they keep changing between on the wiki, and we also ensure that no write with empty data will occur, so if an endpoint has data, that data should no longer disappear with an empty list.

I think this resolves the issue, if you can let me know and then we can close this if it's all good. 👍
