### ISSUE TITLE
Technique data issues

### ISSUE THREAD

**Issue by Articuno-I** [maael/temtem-api#67]
Hi, I noticed two issues with the techniques.json data recently:

- The Technique Course page seems to get scraped as though it's a technique itself
- Awful Song's targets are parsed as `"Single Target Other Team or Ally"`, which is the concatenation of the regular and synergy targets - I'm guessing it should just be `Single Target`, with the change in targetting mentioned in the `synergyEffects`?

Thanks for your work on this btw, having access to the data you provide so easily is extremely useful!

**Comment by maael** [comment]
Hi 👋 Thanks for the feedback, and the interest in the project.

I've now stopped the technique course page itself from being picked up as a technique, and also I've fixed the Awful Song's targeting info collection too - it was the only technique with a targeting change due to synergy, so the only case where this occurred. Going forwards all targeting synergies should be picked up okay and avoid this issue.

The `targets` is just `Single Target` for Awful Song, and the `synergyEffects` are now:

```js
{
  // Other info
  synergyEffect: [
    { damage: 0, type: 'targeting', effect: 'Other Team or Ally' }
  ]
}
```

That should fix this issue, so I'm going to close this! Let me know if you think there's still any issues or anything, and feel free to either reopen this or open a new issue. 👍
