### ISSUE TITLE
Breeding endpoint

### ISSUE THREAD

**Issue by ChrisGarrett23** [maael/temtem-api#96]
What work is needed on the breeding endpoint? if you define a ticket I could handle it for you.

**Comment by maael** [comment]
👋  Heya, thanks for the interest in the project. The rough idea of what I had in mind for the breeding endpoint is here: https://github.com/maael/temtem-api/issues/97. You're more than welcome to tackle it. One thing is I'm not sure how much use an endpoint like that would be, and if it's missing anything that might make it better, suggestions are definitely welcome - it's been a while since I've played Temtem unfortunately. 😅

**Comment by ChrisGarrett23** [comment]
One thing I was hoping to get is what moves a Temtem can teach to others. Right now it is easy to determine what they can learn, but what they can teach is a pain. Might be something we write up based on techniques. I'll check this out, thanks!

**Comment by maael** [comment]
Yeah, I imagine that for something like that, you'd want a list on `breeding` type techniques, with temtem that can know that technique via normal methods (see https://github.com/maael/temtem-api/issues/113).

I'll add a ticket about that, and will close this issue, as the original request was done in https://github.com/maael/temtem-api/issues/97.
